#!/bin/sh


PORT_GAT_LOCATION=/media/disk/workspace/JavaGAT-1.7.1

#OGSA=$GAT_LOCATION/gridlabAdaptors/lib
OGSA=$PORT_GAT_LOCATION/gridlabAdaptors/external/

GEN_CLASSPATH=$OGSA/axis.jar
# GEN_CLASSPATH=/home/alogo/workspace/netbeans/DataTransportServive/lib/axis.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$OGSA/cog-axis.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$OGSA/cog-jglobus-1.2-rob.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$OGSA/cog-tomcat.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$OGSA/commons-discovery.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$OGSA/cryptix-asn1.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$OGSA/cryptix.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$OGSA/cryptix32.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$OGSA/jaxrpc.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$OGSA/jboss-j2ee.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$OGSA/jce-jdk13-120.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$OGSA/jgss.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$OGSA/ogsa-samples.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$OGSA/ogsa.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$OGSA/puretls.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$OGSA/saaj.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$OGSA/servlet.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$OGSA/wsdl4j.jar
# GEN_CLASSPATH=$GEN_CLASSPATH:/cluster/programs/prerequesites/gt4.0.5-all-source-installer/source-trees/wsrf/java/common/source/lib/wsdl4j.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$OGSA/wsif.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$OGSA/xalan.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$OGSA/xmlsec.jar

GEN_CLASSPATH=$GEN_CLASSPATH:$GAT_LOCATION/lib/xercesImpl.jar
#GEN_CLASSPATH=$GEN_CLASSPATH:$GAT_LOCATION/engine/lib/commons-logging.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$GAT_LOCATION/lib/commons-logging-1.1.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$GAT_LOCATION/lib/log4j-1.2.13.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$GAT_LOCATION/lib/log4j-core.jar
GEN_CLASSPATH=$GEN_CLASSPATH:$GAT_LOCATION/lib/xmlParserAPIs.jar 

mkdir -p build/generated

java -cp $GEN_CLASSPATH -Djava.protocol.handler.pkgs=org.globus.net.protocol \
      org.apache.axis.wsdl.WSDL2Java -v --NStoPkg \
      http://fs0.das3.cs.vu.nl:8765/axis/services/Adaptive=adaptive.service  \
      -o src Adaptive.wsdl

